import { HelpCircle } from "lucide-react";

export interface FAQItem {
    id: number;
    question: string;
    answer: string;
    category: 'general' | 'technical' | 'pricing';
}

export const faqData: FAQItem[] = [
    {
        id: 1,
        category: 'general',
        question: 'What is DesignRift and how does it work?',
        answer: 'DesignRift is an intelligent theme generation platform that creates beautiful, accessible themes using Radix color palettes. Simply choose your preferences, and our system generates production-ready themes with built-in dark mode and WCAG compliance in seconds.'
    },
    {
        id: 2,
        category: 'technical',
        question: 'Which frameworks and libraries does DesignRift support?',
        answer: 'DesignRift is framework-agnostic and works with React, Vue, Angular, Svelte, and vanilla JavaScript. It integrates seamlessly with popular styling solutions like Tailwind CSS, Styled Components, Emotion, and CSS-in-JS libraries.'
    },
    {
        id: 3,
        category: 'general',
        question: 'How does DesignRift ensure accessibility compliance?',
        answer: 'Every theme generated by DesignRift automatically meets WCAG 2.1 AA standards. We use intelligent contrast checking, semantic color naming, and ensure proper focus states and keyboard navigation support across all components.'
    },
    {
        id: 4,
        category: 'technical',
        question: 'Can I customize the generated themes beyond the initial setup?',
        answer: 'Absolutely! DesignRift provides a solid foundation that you can extend infinitely. You can override colors, add custom components, modify spacing, and integrate with your existing design system while maintaining accessibility standards.'
    },
    {
        id: 5,
        category: 'general',
        question: 'How does the dark mode functionality work?',
        answer: 'DesignRift includes intelligent dark mode that automatically adapts all colors for optimal contrast and readability. It supports system preference detection, manual toggling, and smooth transitions between light and dark themes.'
    },
    {
        id: 6,
        category: 'technical',
        question: 'What is the Radix color system and why do you use it?',
        answer: 'Radix colors is a professional color system designed for UI development. It provides semantic color scales with perfect contrast ratios, consistent naming conventions, and built-in accessibility features. This ensures your themes are both beautiful and functional.'
    },
    {
        id: 7,
        category: 'pricing',
        question: 'Is DesignRift free to use?',
        answer: 'DesignRift offers a generous free tier that includes basic theme generation and standard color palettes. Premium features like advanced customization, team collaboration, and priority support are available with our paid plans.'
    },
    {
        id: 8,
        category: 'technical',
        question: 'How do I integrate DesignRift themes into my existing project?',
        answer: 'Integration is simple with our one-command setup. Install the DesignRift package, import your generated theme, and you\'re ready to go. We provide detailed documentation and examples for all major frameworks.'
    }
];

export const categories = [
    { id: 'all', label: 'All Questions', icon: <HelpCircle className="w-4 h-4" /> },
    { id: 'general', label: 'General', icon: <HelpCircle className="w-4 h-4" /> },
    { id: 'technical', label: 'Technical', icon: <HelpCircle className="w-4 h-4" /> },
    { id: 'pricing', label: 'Pricing', icon: <HelpCircle className="w-4 h-4" /> }
];