export const themePresets = [
  {
    name: "Modern Minimal",
    colors: {
      canvas: "slate",
      primary: "gray",
      secondary: "mint",
      success: "mint",
      warning: "amber",
      alert: "red",
      info: "blue",
    },
  },
  {
    name: "Twitter",
    colors: {
      canvas: "slate",
      primary: "blue",
      secondary: "sky",
      success: "green",
      warning: "amber",
      alert: "red",
      info: "sky",
    },
  },
  {
    name: "Amethyst Haze",
    colors: {
      canvas: "mauve",
      primary: "violet",
      secondary: "indigo",
      success: "mint",
      warning: "yellow",
      alert: "ruby",
      info: "indigo",
    },
  },
  {
    name: "Catppuccin",
    colors: {
      canvas: "mauve",
      primary: "pink",
      secondary: "teal",
      success: "teal",
      warning: "orange",
      alert: "red",
      info: "blue",
    },
  },
  {
    name: "Kodama Grove",
    colors: {
      canvas: "sage",
      primary: "green",
      secondary: "teal",
      success: "grass",
      warning: "amber",
      alert: "crimson",
      info: "teal",
    },
  },
  {
    name: "Quantum Rose",
    colors: {
      canvas: "gray",
      primary: "pink",
      secondary: "violet",
      success: "lime",
      warning: "amber",
      alert: "ruby",
      info: "violet",
    },
  },
  {
    name: "Elegant Luxury",
    colors: {
      canvas: "sand",
      primary: "crimson",
      secondary: "gold",
      success: "jade",
      warning: "amber",
      alert: "ruby",
      info: "indigo",
    },
  },
  {
    name: "Neo Brut",
    colors: {
      canvas: "slate",
      primary: "pink",
      secondary: "cyan",
      success: "cyan",
      warning: "yellow",
      alert: "tomato",
      info: "blue",
    },
  },
  {
    name: "Mocha Mousse",
    colors: {
      canvas: "olive",
      primary: "brown",
      secondary: "sand",
      success: "green",
      warning: "amber",
      alert: "red",
      info: "teal",
    },
  },
  {
    name: "Notebook",
    colors: {
      canvas: "gray",
      primary: "indigo",
      secondary: "sky",
      success: "mint",
      warning: "yellow",
      alert: "red",
      info: "sky",
    },
  },
  {
    name: "Graphite",
    colors: {
      canvas: "gray",
      primary: "slate",
      secondary: "mint",
      success: "mint",
      warning: "amber",
      alert: "ruby",
      info: "blue",
    },
  },
  {
    name: "Cosmic Night",
    colors: {
      canvas: "mauve",
      primary: "purple",
      secondary: "indigo",
      success: "teal",
      warning: "amber",
      alert: "ruby",
      info: "indigo",
    },
  },
  {
    name: "Nature",
    colors: {
      canvas: "sage",
      primary: "green",
      secondary: "jade",
      success: "grass",
      warning: "amber",
      alert: "crimson",
      info: "jade",
    },
  },
  {
    name: "Amber Minimal",
    colors: {
      canvas: "sand",
      primary: "amber",
      secondary: "lime",
      success: "lime",
      warning: "orange",
      alert: "red",
      info: "sky",
    },
  },
  {
    name: "Solar Dusk",
    colors: {
      canvas: "olive",
      primary: "orange",
      secondary: "amber",
      success: "green",
      warning: "amber",
      alert: "tomato",
      info: "blue",
    },
  },
  {
    name: "Pastel",
    colors: {
      canvas: "mauve",
      primary: "violet",
      secondary: "sky",
      success: "mint",
      warning: "yellow",
      alert: "red",
      info: "sky",
    },
  },
  {
    name: "Bubblegum",
    colors: {
      canvas: "gray",
      primary: "pink",
      secondary: "cyan",
      success: "lime",
      warning: "orange",
      alert: "red",
      info: "cyan",
    },
  },
  {
    name: "Doom 64",
    colors: {
      canvas: "slate",
      primary: "red",
      secondary: "crimson",
      success: "green",
      warning: "amber",
      alert: "crimson",
      info: "blue",
    },
  },
  {
    name: "Perpetuity",
    colors: {
      canvas: "sage",
      primary: "teal",
      secondary: "cyan",
      success: "cyan",
      warning: "amber",
      alert: "ruby",
      info: "sky",
    },
  },
  {
    name: "Tangerine",
    colors: {
      canvas: "sand",
      primary: "orange",
      secondary: "lime",
      success: "lime",
      warning: "yellow",
      alert: "tomato",
      info: "indigo",
    },
  },
  {
    name: "Bold Tech",
    colors: {
      canvas: "gray",
      primary: "purple",
      secondary: "cyan",
      success: "green",
      warning: "amber",
      alert: "ruby",
      info: "blue",
    },
  },
  {
    name: "Supabase",
    colors: {
      canvas: "mauve",
      primary: "green",
      secondary: "cyan",
      success: "teal",
      warning: "orange",
      alert: "red",
      info: "cyan",
    },
  },
  {
    name: "Claymorphism",
    colors: {
      canvas: "olive",
      primary: "blue",
      secondary: "indigo",
      success: "mint",
      warning: "amber",
      alert: "crimson",
      info: "indigo",
    },
  },
  {
    name: "Clean Slate",
    colors: {
      canvas: "slate",
      primary: "gray",
      secondary: "sky",
      success: "mint",
      warning: "yellow",
      alert: "red",
      info: "sky",
    },
  },
];